### ISSUE TITLE
Fails to build with Boost 1.67.0

### ISSUE THREAD

**Issue by junghans** [espressopp/espressopp#216]
```
> [ 1657s] /home/abuild/rpmbuild/BUILD/espressopp-1.9.5/src/integrator/Adress.cpp:459:76:   required from here
> [ 1657s] /usr/include/boost/serialization/access.hpp:116:11: error: 'class std::vector<espressopp::Real3D*>' has no member named 'serialize'
> [ 1657s]          t.serialize(ar, file_version);
> [ 1657s]          ~~^~~~~~~~~
```
Details here: https://bugzilla.suse.com/show_bug.cgi?id=1089815

**Comment by junghans** [comment]
Needs attention!

**Comment by MrTheodor** [comment]
In progress

**Comment by MrTheodor** [comment]
@junghans the issue is with the current code base or with some tagged 1.9.5 version of espp? I have just tried to compile from master with boost 1.67 and there was no problem with Adress.cpp

**Comment by junghans** [comment]
Right, it is v1.9.5 code base!

Time for a new realeas, I guess...

**Comment by MrTheodor** [comment]
Close?

**Comment by junghans** [comment]
@govarguz @stuehn @niktre : Time for another release tag?

**Comment by junghans** [comment]
Problem persists in v2.0!
