### ISSUE TITLE
LatticeBoltzmann.cpp doesn't compile with boost-1.54

### ISSUE THREAD

**Issue by junghans** [espressopp/espressopp#144]
Compile error:
```
[ 1817s] /home/abuild/rpmbuild/BUILD/espressopp-1.9.4/src/integrator/LatticeBoltzmann.cpp: In member function 'void espressopp::integr
ator::LatticeBoltzmann::copyForcesFromHalo()':
[ 1817s] /home/abuild/rpmbuild/BUILD/espressopp-1.9.4/src/integrator/LatticeBoltzmann.cpp:1443:21: error: no matching function for call to 'boost::mpi::environment::environment()'
[ 1817s]     mpi::environment env;
[ 1817s]                      ^
[ 1817s] /home/abuild/rpmbuild/BUILD/espressopp-1.9.4/src/integrator/LatticeBoltzmann.cpp:1443:21: note: candidates are:
[ 1817s] In file included from /usr/include/boost/mpi/collectives/gather.hpp:18:0,
[ 1817s]                  from /usr/include/boost/mpi/collectives/all_gather.hpp:18,
[ 1817s]                  from /usr/include/boost/mpi/collectives.hpp:536,
[ 1817s]                  from /usr/include/boost/mpi.hpp:23,
[ 1817s]                  from /home/abuild/rpmbuild/BUILD/espressopp-1.9.4/src/include/types.hpp:29,
[ 1817s]                  from /home/abuild/rpmbuild/BUILD/espressopp-1.9.4/src/include/python.hpp:28,
[ 1817s]                  from /home/abuild/rpmbuild/BUILD/espressopp-1.9.4/src/integrator/LatticeBoltzmann.cpp:21:
[ 1817s] /usr/include/boost/mpi/environment.hpp:81:3: note: boost::mpi::environment::environment(int&, char**&, bool)
[ 1817s]    environment(int& argc, char** &argv, bool abort_on_exception = true);
[ 1817s]    ^
[ 1817s] /usr/include/boost/mpi/environment.hpp:81:3: note:   candidate expects 3 arguments, 0 provided
[ 1817s] /usr/include/boost/mpi/environment.hpp:48:22: note: boost::mpi::environment::environment(const boost::mpi::environment&)
[ 1817s]  class BOOST_MPI_DECL environment : noncopyable {
[ 1817s]                       ^
[ 1817s] /usr/include/boost/mpi/environment.hpp:48:22: note:   candidate expects 1 argument, 0 provided
```
Details [here](https://github.com/espressopp/espressopp/files/656136/log.txt) (from https://build.opensuse.org/package/show/science/python-espressopp)

**Comment by niktre** [comment]
is fixed in #96 

waiting for approval :-)

**Comment by junghans** [comment]
That is too much for me to review ;-)

**Comment by niktre** [comment]
then just accept it :-)))
