### PR TITLE
bump version to 2.0.0

### LINKED ISSUE #216: Fails to build with Boost 1.67.0
```
> [ 1657s] /home/abuild/rpmbuild/BUILD/espressopp-1.9.5/src/integrator/Adress.cpp:459:76:   required from here
> [ 1657s] /usr/include/boost/serialization/access.hpp:116:11: error: 'class std::vector<espressopp::Real3D*>' has no member named 'serialize'
> [ 1657s]          t.serialize(ar, file_version);
> [ 1657s]          ~~^~~~~~~~~
```
Details here: https://bugzilla.suse.com/show_bug.cgi?id=1089815

### PR DESCRIPTION
**Pull request by niktre**
Fix #216

### CODE REVIEW

**Comment by junghans** [comment]
We need a `v2.0.0` tag!
