### ISSUE TITLE
MPI4PY issue on macbook

### ISSUE THREAD

**Issue by niktre** [espressopp/espressopp#9]
cmake went normally with -DEXTERNAL_BOOST=OFF -DEXTERNAL_MPI4PY=OFF

then, at the very end of "make install" i get this:
Linking CXX shared library ../_espressopp.so
[100%] Built target _espressopp
[100%] Building C object contrib/mpi4py/CMakeFiles/MPI.dir/mpi4py-1.3/src/MPI.c.o
Linking C shared library MPI.so
Undefined symbols for architecture x86_64:
  "_MPI_Type_create_f90_complex", referenced from:
      ___pyx_pf_6mpi4py_3MPI_8Datatype_18Create_f90_complex in MPI.c.o
  "_MPI_Type_create_f90_integer", referenced from:
      ___pyx_pf_6mpi4py_3MPI_8Datatype_16Create_f90_integer in MPI.c.o
  "_MPI_Type_create_f90_real", referenced from:
      ___pyx_pf_6mpi4py_3MPI_8Datatype_17Create_f90_real in MPI.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [contrib/mpi4py/MPI.so] Error 1
make[1]: *** [contrib/mpi4py/CMakeFiles/MPI.dir/all] Error 2
make: *** [all] Error 2

is this my laptop's problem or something is wrong with mpi4py?

**Comment by pdebuyl** [comment]
This is weird but still, can you try:
- `git clean -fx`
- `rm -rf CMakeFiles CMakeCache.txt`

then run cmake again and build?

**Comment by niktre** [comment]
Hi Pierre,
your suggestion does not solve it. 
Actually, couple of weeks ago a had seen a similar behavior on another computer. It was a Linux-based desktop and building went fine, but importing espressopp into python gave an error in mpi4py.

By the way, for me everything works with an external mpi4py v1.3.1

Does anybody see problems with an internal mpi4py or am I the only one?

**Comment by pdebuyl** [comment]
The travis builds https://travis-ci.org/espressopp/espressopp are ok with internal mpi4py. I just recompiled on my computer (debian jessie) to check and it's all fine.

I suspect a bad combination of python and compilers. Do you use the system Python, conda, brew, ?

The error seems really related to type declarations. A "clean" chain of tools usually helps, that is having gcc, g++, gfortran, openmpi, boost, fftw from the same vendor.

**Comment by niktre** [comment]
Ok, found a solution. It was my problem. No idea why, but permissions were wrong, i.e. _espressopp.so was owned by root. Thanks!
